// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_KEY = SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY || "";

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("ERRO CRÍTICO: Variáveis de ambiente do Supabase não encontradas. Verifique o arquivo .env");
  try { localStorage.setItem('supabase_offline', 'true'); localStorage.setItem('supabase_connection_status', 'error'); } catch { /* noop */ }
}

// Cria o cliente mesmo com strings vazias para não quebrar a importação, 
// mas as chamadas falharão e serão tratadas nos services.
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_KEY, 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      // Adiciona headers globais para debug se necessário
      headers: { 'x-application-name': 'flexi-train-reports' }
    }
  }
);
